"use client";

import { useMemo, useState } from "react";
import type { CompanyProfile } from "@/lib/ai/schemas/company-profile";
import { artifactToMarkdown } from "@/lib/markdown";

type InputRow = { id: number; kind: string; title: string; content: string; createdAt: number };
type ArtifactRow = { id: number; version: number; contentJson: string; modelUsed: string; createdAt: number };

const kindLabels: Record<string, string> = { discovery_notes: "Discovery notes", transcript: "Transcript", public_doc: "Public doc", other: "Other" };

function ProfileView({ profile }: { profile: CompanyProfile }) {
  return <div className="space-y-5 text-sm text-slate-200">
    <section><h3 className="font-semibold text-white">Company Overview</h3><p className="mt-1 text-slate-300">{profile.companyOverview}</p></section>
    <section><h3 className="font-semibold text-white">Business Segments</h3><div className="mt-2 space-y-2">{profile.businessSegments.map((s, i) => <div key={i} className="rounded-lg bg-slate-950 p-3"><b>{s.name}</b><p>{s.description}</p><p className="text-slate-400">Planning: {s.relevanceToPlanning}</p></div>)}</div></section>
    <section><h3 className="font-semibold text-white">Manufacturing Footprint</h3><p className="mt-1 text-slate-300">{profile.manufacturingFootprint}</p></section>
    <section><h3 className="font-semibold text-white">Supply Chain Characteristics</h3><ul className="mt-1 list-disc pl-5"><li>Demand: {profile.supplyChainCharacteristics.demandPattern}</li><li>Product: {profile.supplyChainCharacteristics.productComplexity}</li><li>Network: {profile.supplyChainCharacteristics.networkComplexity}</li></ul></section>
    <section><h3 className="font-semibold text-white">Current Systems</h3><ul className="mt-1 space-y-1">{profile.currentSystems.map((s, i) => <li key={i}>• <b>{s.system}</b> ({s.sentiment}) — {s.role}</li>)}</ul></section>
    <section><h3 className="font-semibold text-white">Stated Pain Points</h3><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-slate-400"><th>Pain</th><th>Evidence</th><th>Source</th><th>Severity</th></tr></thead><tbody>{profile.statedPainPoints.map((p, i) => <tr key={i} className="border-t border-slate-800"><td className="py-2 pr-2">{p.pain}</td><td className="py-2 pr-2">“{p.evidence}”</td><td className="py-2 pr-2">{p.source}</td><td className="py-2">{p.severity}</td></tr>)}</tbody></table></div></section>
    <section><h3 className="font-semibold text-white">Strategic Priorities</h3><ul className="mt-1 list-disc pl-5">{profile.strategicPriorities.map((x, i) => <li key={i}>{x}</li>)}</ul></section>
    <section><h3 className="font-semibold text-white">Stakeholders</h3><ul className="mt-1 space-y-1">{profile.stakeholders.map((s, i) => <li key={i}>• <b>{s.name}</b>, {s.role} — {s.disposition}. {s.notes}</li>)}</ul></section>
    <section><h3 className="font-semibold text-white">Open Questions</h3><ol className="mt-1 list-decimal pl-5">{profile.openQuestions.map((x, i) => <li key={i}>{x}</li>)}</ol></section>
    <section><h3 className="font-semibold text-white">Confidence Notes</h3><p className="mt-1 text-slate-300">{profile.confidenceNotes}</p></section>
  </div>;
}

export function EngagementWorkspace({ engagementId, accountName, inputs, artifacts }: { engagementId: number; accountName: string; inputs: InputRow[]; artifacts: ArtifactRow[] }) {
  const [editing, setEditing] = useState<InputRow | null>(null);
  const [selectedVersion, setSelectedVersion] = useState(artifacts[0]?.version ?? 0);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const selectedArtifact = artifacts.find((a) => a.version === selectedVersion) ?? artifacts[0];
  const profile = useMemo(() => selectedArtifact ? JSON.parse(selectedArtifact.contentJson) as CompanyProfile : null, [selectedArtifact]);
  async function generate() { setGenerating(true); setError(""); try { const res = await fetch(`/api/engagements/${engagementId}/profile`, { method: "POST" }); const json = await res.json(); if (!res.ok) throw new Error(json.error ?? "Generation failed"); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Generation failed"); } finally { setGenerating(false); } }
  async function copyMarkdown() { if (profile) await navigator.clipboard.writeText(artifactToMarkdown(profile)); }

  return <main className="mx-auto max-w-7xl px-6 py-8"><div className="mb-4 flex gap-3 text-sm"><a className="text-cyan-300" href="/">← Engagements</a><a className="rounded border border-slate-700 px-3 py-1" href={`/engagements/${engagementId}/discover`}>Discover</a><a className="rounded bg-cyan-400 px-3 py-1 font-semibold text-slate-950" href={`/engagements/${engagementId}`}>Inputs & Profile</a></div><h1 className="text-3xl font-semibold">{accountName}</h1><div className="mt-6 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Inputs</h2><div className="mt-4 space-y-3">{inputs.map((row) => <article key={row.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{row.title}</h3><p className="mt-1 text-xs text-slate-400"><span className="rounded bg-cyan-950 px-2 py-1 text-cyan-200">{kindLabels[row.kind]}</span> · {new Date(row.createdAt).toLocaleString()} · {row.content.length.toLocaleString()} chars</p></div><button onClick={() => setEditing(row)} className="text-sm text-cyan-300">View/Edit</button></div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm text-slate-400">{row.content}</p></article>)}</div>
      <form action={`/api/engagements/${engagementId}/inputs`} method="post" className="mt-5 rounded-xl border border-slate-800 p-4"><h3 className="font-semibold">Add Input</h3><select name="kind" className="mt-3 w-full rounded bg-slate-950 p-2"><option value="discovery_notes">Discovery notes</option><option value="transcript">Transcript</option><option value="public_doc">Public doc</option><option value="other">Other</option></select><input name="title" required placeholder="Title" className="mt-3 w-full rounded bg-slate-950 p-2"/><textarea name="content" required placeholder="Paste content only — no file upload" className="mt-3 h-40 w-full rounded bg-slate-950 p-2"/><button className="mt-3 rounded bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Add Input</button></form>
    </section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Profile</h2><button disabled={inputs.length === 0 || generating} onClick={generate} className="rounded bg-cyan-400 px-4 py-2 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:bg-slate-700">{generating ? "Generating…" : selectedArtifact ? "Regenerate" : "Generate Profile"}</button></div>{error && <div className="mt-4 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-100">{error}<button onClick={generate} className="ml-3 underline">Retry</button></div>}{artifacts.length > 1 && <label className="mt-4 block text-sm">Version <select value={selectedVersion} onChange={(e) => setSelectedVersion(Number(e.target.value))} className="ml-2 rounded bg-slate-950 p-2">{artifacts.map((a) => <option key={a.id} value={a.version}>v{a.version}</option>)}</select></label>}{selectedArtifact && <p className="mt-3 text-xs text-slate-400">Model: {selectedArtifact.modelUsed} · {new Date(selectedArtifact.createdAt).toLocaleString()}</p>}{profile ? <><button onClick={copyMarkdown} className="mt-4 rounded border border-slate-700 px-3 py-2 text-sm text-slate-200">Copy as Markdown</button><div className="mt-5"><ProfileView profile={profile}/></div></> : <p className="mt-8 rounded-xl border border-dashed border-slate-700 p-6 text-slate-400">Add pasted inputs, then generate the first company profile.</p>}</section>
  </div>{editing && <div className="fixed inset-0 bg-black/70 p-6"><form action={`/api/engagements/${engagementId}/inputs/${editing.id}`} method="post" className="mx-auto max-w-3xl rounded-2xl bg-slate-900 p-5"><div className="flex justify-between"><h3 className="text-xl font-semibold">View / Edit Input</h3><button type="button" onClick={() => setEditing(null)}>Close</button></div><select name="kind" defaultValue={editing.kind} className="mt-4 w-full rounded bg-slate-950 p-2"><option value="discovery_notes">Discovery notes</option><option value="transcript">Transcript</option><option value="public_doc">Public doc</option><option value="other">Other</option></select><input name="title" required defaultValue={editing.title} className="mt-3 w-full rounded bg-slate-950 p-2"/><textarea name="content" required defaultValue={editing.content} className="mt-3 h-72 w-full rounded bg-slate-950 p-2"/><div className="mt-3 flex gap-3"><button className="rounded bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Save</button><button name="intent" value="delete" className="rounded bg-red-900 px-4 py-2 text-white">Delete</button></div></form></div>}</main>;
}
